server.port: 9090

security.oauth2:
  client:
    client-id: client-id
    client-secret: client-secret
  resource:
    token-info-uri: http://localhost:8081/oauth/check_token

logging.level:
  org.springframework:
    security: debug
    boot: debug